import Head from 'next/head'
import Script from 'next/script'
import { Inter } from 'next/font/google'
import Intro from '@/components/intro'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Arefin's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />                
      </Head>
      <main className='font-nunito'>        
        {/* intro section */}
        <Intro />
      </main>      
    </>
  )
}
